"""Shared constants used across multiple STL-manager scripts.

Centralised here to eliminate duplication and keep definitions in sync.
"""

from typing import Dict, Set

# ---------------------------------------------------------------------------
# OS noise files — filenames generated by macOS / Windows that are not models
# ---------------------------------------------------------------------------
NOISE_FILENAMES: Set[str] = {".ds_store", "thumbs.db", "desktop.ini"}

# ---------------------------------------------------------------------------
# File extensions considered "meaningful" 3D model or source files
# ---------------------------------------------------------------------------
MEANINGFUL_EXTS: Set[str] = {
    "stl", "obj", "ztl",           # common 3D model formats / ZBrush
    "lys", "lychee", "3mf",        # slicer / project formats
    "step", "stp",                 # CAD formats
}
ARCHIVE_EXTS: Set[str] = {"zip", "rar", "7z"}

# ---------------------------------------------------------------------------
# Kit detection tokens — child folder names implying a modular squad kit
# ---------------------------------------------------------------------------
KIT_CHILD_TOKENS: Set[str] = {
    "body", "bodies", "torsos", "torso",
    "head", "heads", "helmet", "helmets",
    "arm", "arms", "left arm", "right arm",
    "hand", "hands",
    "weapon", "weapons", "ranged", "melee", "flamer", "flamers",
    "bits", "bitz", "accessories", "options",
    "shields", "backpacks", "shoulder pads", "pauldrons",
    "shoulders", "legs", "bases", "base",
}

KIT_PARENT_HINTS: Set[str] = {
    "complete library", "full kit", "all parts", "modular", "complete set",
    "upgrade set", "bits library", "bitz library", "kit", "complete pack", "full pack",
}

# ---------------------------------------------------------------------------
# Default tabletop scale per game system (denominator of 1:N ratio)
# ---------------------------------------------------------------------------
SYSTEM_DEFAULT_SCALE_DEN: Dict[str, int] = {
    "w40k": 56,
    "aos": 56,
    "heresy": 56,
    "old_world": 56,
}

SYSTEM_DEFAULT_SCALE_NAME: Dict[str, str] = {
    "w40k": "28mm heroic",
    "aos": "28mm heroic",
    "heresy": "28mm heroic",
    "old_world": "28mm heroic",
}

# ---------------------------------------------------------------------------
# AoS faction tokens — phrase → faction_key mapping
# ---------------------------------------------------------------------------
AOS_FACTION_TOKENS_MAP: Dict[str, str] = {
    "flesh eater courts": "flesh_eater_courts",
    "soulblight gravelords": "soulblight_gravelords",
    "nighthaunt": "nighthaunt",
    "stormcast eternals": "stormcast_eternals",
    "seraphon": "seraphon",
    "kharadron overlords": "kharadron_overlords",
    "gloomspite gitz": "gloomspite_gitz",
    "orruk warclans": "orruk_warclans",
    "ogor mawtribes": "ogor_mawtribes",
    "sylvaneth": "sylvaneth",
    "cities of sigmar": "cities_of_sigmar",
    "skaven": "skaven",
    "slaves to darkness": "slaves_to_darkness",
    "blades of khorne": "blades_of_khorne",
    "disciples of tzeentch": "disciples_of_tzeentch",
    "maggotkin of nurgle": "maggotkin_of_nurgle",
    "hedonites of slaanesh": "hedonites_of_slaanesh",
    "beasts of chaos": "beasts_of_chaos",
    "sons of behemat": "sons_of_behemat",
    "fyreslayers": "fyreslayers",
    "lumineth realm lords": "lumineth_realm_lords",
    "daughters of khaine": "daughters_of_khaine",
    "idoneth deepkin": "idoneth_deepkin",
    "ossiarch bonereapers": "ossiarch_bonereapers",
}

# Convenience list for quick string-in-text matching
AOS_FACTION_TOKENS = list(AOS_FACTION_TOKENS_MAP.keys())

# AoS: map leaf faction keys → Grand Alliance
AOS_LEAF_TO_GRAND: Dict[str, str] = {
    # Order
    "stormcast_eternals": "order",
    "cities_of_sigmar": "order",
    "fyreslayers": "order",
    "kharadron_overlords": "order",
    "lumineth_realm_lords": "order",
    "idoneth_deepkin": "order",
    "daughters_of_khaine": "order",
    "seraphon": "order",
    "sylvaneth": "order",
    # Chaos
    "slaves_to_darkness": "chaos",
    "blades_of_khorne": "chaos",
    "disciples_of_tzeentch": "chaos",
    "maggotkin_of_nurgle": "chaos",
    "hedonites_of_slaanesh": "chaos",
    "beasts_of_chaos": "chaos",
    "skaven": "chaos",
    # Death
    "flesh_eater_courts": "death",
    "soulblight_gravelords": "death",
    "nighthaunt": "death",
    "ossiarch_bonereapers": "death",
    # Destruction
    "gloomspite_gitz": "destruction",
    "orruk_warclans": "destruction",
    "ogor_mawtribes": "destruction",
    "sons_of_behemat": "destruction",
}
